### ISSUE TITLE
Love your shaders

### ISSUE THREAD

**Issue by sanchez** [FlynnsPixel/GLSL-shaders#1]
Hey,

I really like your shaders and the effects you have. Do you mind explaining what is being achieved from here downwards: https://github.com/kiwipxl/GLSL-shaders/blob/master/outline.glsl#L66

I noticed it is similarly repeated on the glow, bloom, and blur effects and would love to understand what it is doing.

Thanks!

**Comment by sanchez** [comment]
My understand is that you are sampling the surrounding area but still a bit confused by code. Any explanation is greatly appreciated thanks!

**Comment by kiwipxl** [comment]
Hey Daniel!

It's been a very long time since writing these, and I haven't touched
shader code in a while either, but I can do my best to explain!

Gaussian blur:
For every pixel (fragment), we grab the pixel colours around it (it's
neighbors).
Let's say the blur_size or outline_thickness is 1. It will sample a 9x9
square with the current fragment in the center. So that'll be 4 pixels on
each side (up, down, left, right).
If the blur_size is 0.5, it'll sample half of that (4.5x4.5 square).
If the blur_size is greater than 1, it'll start skipping pixels. This isn't
very clever! The result won't look so good.

Outline shader:
Let's say you have a texture of mario with alpha/transparency background.
The idea here was to apply an outline to the transparent pixels only around
mario.

We do this by sampling pixel alpha instead of pixel colour when applying
our Gaussian blur. If you imagine mario was black and the background was
white, when we apply the blur, the black would extend outwards. We can use
this as an outline.

So for every pixel that is transparent (so that we don't overwrite Mario's
pixels) we sample our blur and turn the pixel black (or outline_colour) if
the sum is greater than some number.


Hope that helps in some way. It is difficult to explain without using
images, so instead it might be better to follow a tutorial online (Gaussian
blur glsl).

Also I'm not very experienced with shaders! These shaders were just a
learning experience for me and I posted them on GitHub. There are much
better and more efficient techniques out there written by smart people.

**Comment by sanchez** [comment]
This does help tremendously thank you very much
